# This is a basic workflow to help you get started with Actions

name: git-ipfs-rehost

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # clones the new submodule repository
  clone:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      # Install IPFS
      - name: Install IPFS
        run: wget https://dist.ipfs.tech/kubo/v0.15.0/kubo_v0.15.0_linux-amd64.tar.gz && tar -xvzf kubo_v0.15.0_linux-amd64.tar.gz && cd kubo && sudo bash install.sh
      - name: Check Verison
        run: ipfs --version

  # Rehosts the new repository
  #rehost:
